language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - 'node'

env:
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g coveralls@2 nyc@10.3

script:
  - npm run test

after_success:
  - npm run test:travis

sudo: false
